version: "3.8"
services:
  backend:
    #!image: "sarasapepe:v1" #ESTA LÍNEA TIRA UN WARNING EN EL RUNNING
    container_name: backend
    build:
      context: .
      dockerfile: back/Dockerfile.dev
    environment:
      - MYSQL_HOST=database
      - MYSQL_DB_NAME=clasesparticulares
      - MYSQL_USER=root
      - MYSQL_PASSWORD=#$#2Jshdw3@@3ajs###sssSSDdssa
    #!restart: unless-stopped
    ports:
      - "4000:3000"
    depends_on: 
      - database
    volumes:
      - ./back:/app                

  database:
    container_name: database
    image: mysql:8
    #!restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=#$#2Jshdw3@@3ajs###sssSSDdssa
      - MYSQL_DATABASE=clasesparticulares
    volumes:
      - app_database:/var/lib/mysql

  frontend:
    #!image: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: front/Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_URL_API=http://localhost:4000/api/opiniones
      - REACT_APP_EMAILJS_SERVICEID=service_sxi0tqs
      - REACT_APP_EMAILJS_TEMPLATEID=template_8blwdpd
      - REACT_APP_EMAILJS_APIPUBKEY=EigCH_bWKVIFtYyAq
      #!- BACK_HOST=backend
    #!restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app

volumes:
  app_database: 

  
    
  

