version: "3.8"
services:
  backend:
    container_name: proyecto-clases_backend
    build:
      context: .
      dockerfile: back/Dockerfile.dev
    environment:
      - MYSQL_HOST=database
      - MYSQL_DB_NAME=clasesparticulares
      - MYSQL_USER=root
      - MYSQL_PASSWORD=#$#2Jshdw3@@3ajs###sssSSDdssa
    ports:
      - "4000:3000"
    depends_on: 
      - database
    volumes:
      - ./back:/app                

  database:
    container_name: proyecto-clases_database
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=#$#2Jshdw3@@3ajs###sssSSDdssa
      - MYSQL_DATABASE=clasesparticulares
    volumes:
      - app_database:/var/lib/mysql
      - ./clasesparticulares.sql:/clasesparticulares.sql

  frontend:
    container_name: proyecto-clases_frontend
    build:
      context: .
      dockerfile: front/Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_URL_API=http://localhost:4000/api/opiniones
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app

volumes:
  app_database: 

  
    
  

