version: "3.8"
services:
  backend:
    container_name: proyecto-clases_backend
    build:
      context: .
      dockerfile: back/Dockerfile.prod
    environment:
      - MYSQL_HOST=database
      - MYSQL_DB_NAME=clasesparticulares
      - MYSQL_USER=root
      - MYSQL_PASSWORD=#$#2Jshdw3@@3ajs###sssSSDdssa
    restart: unless-stopped
    depends_on: 
      - database
    networks:
      - default
      - proxy_manager_default

  database:
    container_name: proyecto-clases_database
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=#$#2Jshdw3@@3ajs###sssSSDdssa
      - MYSQL_DATABASE=clasesparticulares
    volumes:
      - app_database:/var/lib/mysql
      - ./clasesparticulares.sql:/clasesparticulares.sql

  frontend:
    container_name: proyecto-clases_frontend
    build:
      context: .
      dockerfile: front/Dockerfile.prod
    restart: unless-stopped
    networks:
      - default
      - proxy_manager_default

volumes:
  app_database:

networks:
  proxy_manager_default:
    external: true