# STAGE 1:
FROM node:18.6-alpine AS BUILD

WORKDIR /app

COPY ./front/package*.json /app
COPY ./front/public /app/public
COPY ./front/src /app/src

RUN apk update
RUN apk add --upgrade xdg-utils
RUN npm install

ENV NODE_OPTIONS=--max-old-space-size=900

RUN npm run build


# STAGE 2:
FROM node:18.6-alpine

COPY --from=BUILD /app/build /app

RUN npm install -g serve

EXPOSE 3000

CMD [ "serve", "-s", "/app", "-l", "3000" ]